### PR TITLE
playlists fixes

### PR DESCRIPTION
**Pull request by Moyster**
Hi,

When I use the ambilight plugin with other plugins such as Cinema Vision, the ambilight plugin stop working when multiple short videos are played.
CinemaVision adds multiple shorts before a movie (trailer, theater intro, dolby/atmos screens etc...) and the ambilight plugin in ambilight mode doesn't survive CinemaVision intro.

Fixes from koying solved the problem here.

### CODE REVIEW

**Comment by Moyster** [comment]
Everything comes in threes ? :)

**Comment by Moyster** [comment]
Hello, 

Any infos on why this ain't getting merged ?

Thanks

**Comment by mpolednik** [comment]
Haven't had time to play with it yet, if you are really sure it doesn't break anything (with or without additional plugins) feel free to answer and I'll merge (equivalent of verification) -- really miss gerrit's code review/verification split here!

**Comment by Moyster** [comment]
Hoi, my bad, never gave it more than 2-3 movies since rebasing, but it works for me since before summer both on arm/x86 and it's merged :) ty

**Comment by mpolednik** [comment]
Didn't break anything for me, so... 👍

**Comment by Moyster** [comment]
does that mean you finally have a lightstrip to toy with ? :')

**Comment by mpolednik** [comment]
No, working on that part though; wanted to make sure it works with what I have (basic kit).

Planning bigger changes when I get my hands on the strip -- mostly to enable light grouping and fine grained behavior configuration (e.g. ambilight on strips, theater mode on other bulbs).

**Comment by Moyster** [comment]
Oh well, that's still good news :)

If you have a bit of free times in the coming days, could you write a very basic "how to run the tests" ? I got discouraged trying anything since I couldn't figure (in a timely manner) how to run them.
This might also help other people (hopefully) looking around to get started :)

**Comment by mpolednik** [comment]
Frankly, I haven't really run them as looking over them - they're not really related/helpful. We have issue #6 as a reminder we definitely want some proper tests (mostly unit, not really testing the bulbs).

**Pull request merged**
