### PR TITLE
Fix #60 - remove playlistpos reference.

### LINKED ISSUE #60: Lights undim when video ends
How to make the lights go back to 100% when the show automatically comes to an end.

### PR DESCRIPTION
**Pull request by tdb**
This is a simple fix for #60. `playlistpos` no longer exists, so it can't be used in `onPlayBackEnded`. Whilst here, remove `playlistlen` too, since it's only set and never used.

I'm not sure about the original use of this stuff in #18 though, and why it was partially removed later. It probably wouldn't be too hard to fix it by re-adding the code instead. I'd be happy update my pull request to do that if preferred.

### CODE REVIEW

**Comment by Moyster** [comment]
Hi, thanks for your pull,  
Initially the playlist "hack" was intended for playlist/plugins adding extra (intros/outros, trailers..), if you play a list, then the plugin would stop after the first video ends and either stay in the dark or fixed lights.  
If you want to update your PR, you can test the plugin I found the problem on initially, "cinemavision".  
It was probably made broken during mpolednik's refactoring.  

It would be nice to keep and fix those bits, as it also fixes : https://github.com/mpolednik/script.kodi.hue.ambilight/issues/67 (at least, I assume)  

Thank you :)

**Comment by tdb** [comment]
@Moyster ok, done. I've tested this still fixes #60. Not sure about #67, but it might fix it too. I haven't tested with cinemavision though, but the code is back how it was in #18, so it has a good chance of being fine - shouldn't be any worse at least :-)

**Comment by Moyster** [comment]
@tdb awesome, thanks :)  
Will give that a test later today when I get home, see if cinemavision finally "git gud". Looking at your commit, I'm pretty sure you nailed both https://github.com/mpolednik/script.kodi.hue.ambilight/issues/60 & https://github.com/mpolednik/script.kodi.hue.ambilight/issues/67 :+1:

**Comment by Moyster** [comment]
Well it works fine here, tested cinemavision and playing a few episodes in a playlist (fast-forwarding 'til 30sec before the end).  
A single movie/episode or a playlist also undims the lights according to the settings (I used the hue app on mobile to set my lights to 63%, started kodi, played an episode and waited for the end to undim the lights, hue app was back to 63%).  
Also found the commit _where it all started_ :  
https://github.com/mpolednik/script.kodi.hue.ambilight/commit/51dfb710a71e83493dc8a71b826a0a95446e91ee#diff-e87f4dd869f897586689ccfd0fa643d5L89  

@tdb thanks again, let's summon @mpolednik for the merge :)

**Comment by Macpatto** [comment]
@Moyster @Moyster So, being the case in which I was always wanted for the script to that. Are you guys going to release a fix or update on the plug in?

**Comment by Moyster** [comment]
Hi @Macpatto @Macpatto, you can just download the branch tdb pushed his fix to :  
https://github.com/tdb/script.kodi.hue.ambilight/tree/fix-60  

I have no powers here, I can't merge PR nor close issues, we need to wait mpolednik to merge :)

**Comment by Macpatto** [comment]
@Moyster awesome.. hopefully @mpolednik can't merge it. Thanks.

**Pull request merged**
