### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by unlimitedggames**
Minimun threshold value get fixed.

### CODE REVIEW

**Comment by Moyster** [comment]
Hi there,  
Thanks for the PR :) It's wierd travis failed, your change doesn't look like it breaks anything (I'll give this a short test during today)  
Anyway, It looks good, I guess you tried it first, what's up with the settings.xml value tho :  
https://github.com/mpolednik/script.kodi.hue.ambilight/blob/master/resources/settings.xml#L115
Is L.115 : `"enable="eq(-1,true)"` still valid ?

**Comment by Moyster** [comment]
Just realised it was a "v16" commit, v17 already fixed :)

**Comment by unlimitedggames** [comment]
Yeah. Its for v16, using it with a Kodi on Rasp, haven't updated yet :p

**Comment by Moyster** [comment]
Well, that's probably why the tests fails, so it's not that important :p I won't test v16 (because I updated to 17.3 everywhere already).  
Looking at the change tho, I assume it's safe to merge, it's pretty much just a fix backported from v17 to v16. Let's summon @mpolednik for _da-merge_ ;)  
Thanks @unlimitedggames

**Comment by mpolednik** [comment]
Yeah, small todo: make sure v16 travis doesn't complain.

**Pull request merged**
