### PR TITLE
Rewrite (v1.0?!)

### PR DESCRIPTION
**Pull request by mpolednik**
So, the refactoring is somewhat shaping nicely I believe. It may be time to move on to master. About the patches themself, they are huge. I've managed to rewrite most of the code and untangle the state to current state_change and new Controller objects. Additionally, tests are also added (running on Travis, manually launchable by `PYTHONPATH=resources/lib pytest -v` in project's root dir (e.g. ~/script.kodi.hue.ambilight).

Whole configuration is reworked, lights can now be dynamically selected from/to ambilight and theatre groups. As for the ambilight algorithm itself, I believe there are some changes that will require further testing and fine-tuning to get to the point where we were. There is no hue/saturation oveerride functionality *yet*; should be quite trivial to add but time consuming.

Annoyance I have noticed since owning the lighstrip (not directly related to the rework): it's color gamut is brutal compared to v1 bulbs. Anyone who wants to play with the constants in resources/lib/image.py is more than welcome to fix the difference. :) (I'd eventually think of light-specific gamut corrections now that the plugin is kinda more spread.)

Known issues: 
- credits undimming was removed, will be reimplemented when the state checking gets more robust
- when configuring groups, for window to properly react, one has to press OK after selecting the bulbs and then OK to exit the configuration and re-enter it

Should solve: #24 #21 #16 #15 #7 #6 #5 
Only v17+ is supported.

### CODE REVIEW

**Comment by JesCR** [comment]
Thanks!

**Comment by AnthraxLeprosyPi** [comment]
Wow. this sounds very good!

So, is this ready for a test drive now?

**Comment by mpolednik** [comment]
I hope it is. :)

The very essential stuff (like bridge connection) works fine, theater works for me for the first time in a way I'd expect. Ambilight may be too aggressive, but it may be that I'm not used to lightstrip.

**Comment by mpolednik** [comment]
Oh, and your opinions on default behavior (both ambilight/theater) are more than welcome! I've tweaked it in a way I'm happy about, but I haven't previously used theater mode much...

Current default behavior is:
playback starts: dim to 30 brightness (~super low)
playback pause: undim to last state (state is saved each time playback starts)
playback stop: undim to last state (state is saved each time playback starts)

^^^^^^^
Does this seem reasonable?

**Comment by AnthraxLeprosyPi** [comment]
Allright will test all of next week...

**Comment by JesCR** [comment]
So, i want to try it!
Where is the right download?
Sorry, but i'm lost in github with all this "pull-merge-commit", i'm looking for a zip :)

I will compare with the old versions with my setup, two blooms in ambilight and (i'll try) two lights in theater mode...

**Comment by mpolednik** [comment]
On the project page use the branch switch and then you can download the zip.

Or use https://github.com/mpolednik/script.kodi.hue.ambilight/archive/refactoring-v9-candidate.zip directly :)

**Comment by JesCR** [comment]
Thanks again!

**Comment by Macpatto** [comment]
mpolednik.. 
I've just tested on my Kodi Krypton 17 with a Konfluence skin and all I can say that it is awesome.  
The only hiccup I found is that if I want to watch another movie or tv show right after,  the lights won't dimmed anymore until I restart the script manually.
I am running it with a hue lightstrip for the Ambilight and two bulbs for Theatre which works really well.
Thumbs Up and keep up the good work!!

**Comment by hstamas** [comment]
mpolednik. Here is how I imagine theater mode working. 

Have the ability to leave 1 light on at movie start. This way any one who has a light behind the TV can use it as bias lighting. Allow that light to randomly choose hue/saturation for people with Hue lightstrips. 

For pause  state, allow an option to only turn on certain lights. I use thus state for when we pause a movie when someone needs to go to the bathroom or get a snack. That way you can just turn on one light so they can see where they are going. Pressing play again returns the lights to their "play" state.

**Comment by mpolednik** [comment]
@Macpatto Pushed a fix to that, starting new playback should keep the addon working. Tested it quickly myself, would love to hear if downloading new zip and installing it works for you.

@hstamas For the single "static" light, I'm not sure the addon should be handling that. You can do that by simply not adding the light to any group and setting it via other means. That being said, if "static lights" group is important for you, it's not a problem to add that. As for the undimming of only specific lights, I think that's great idea and should be doable.

**Comment by hstamas** [comment]
I would definitely request that the single static light be included in some way as using it as a bias light, you definitely want it included in the whole on/off scenarios when using the addon.
I.E.: when a movie starts turnoff the room lights and turn on the bias light behind TV. When movie ends, turn on room lights and turn off bias light.

**Comment by mpolednik** [comment]
@hstamas Added ability to set up subgroup of theater lights that will be undimmed during pause... I'm thinking the whole static like thing is almost the same case, just for the ambilight group. :)

**Comment by hstamas** [comment]
That's great @mpolednik. Would using the ambilight group be able to be set to NOT change colors while the video plays? That's the big difference between a dynamic ambilight setup and bias lighting. I find a changing light while the movie plays headache inducing personally.

**Comment by mpolednik** [comment]
@hstamas Well that's what I'm investigating... But I've so far opted for new "static lights" group.

Currently thinking of following behavior:

playback starts:
- save state (I assume the light would normally be off/handled by you)
- light on, brightness to 150 (default, configurable)
playback paused:
- light off
playback stops:
- restore initial state

**Comment by mpolednik** [comment]
@hstamas Feel free to try it now, the static group is there (as a standalone group).

I'm also getting happy with the code, so unless someone is really concerned about this moving to master I'll try to merge it asap.

**Comment by JesCR** [comment]
I'm getting this error:

```
21:00:55.418 T:139713969104640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Light' object has no attribute 'hue'
                                            Traceback (most recent call last):
                                              File "/script.kodi.hue.ambilight/default.py", line 296, in <module>
                                                hue = Hue(settings, args)
                                              File "/script.kodi.hue.ambilight/default.py", line 115, in __init__
                                                self.update_controllers()
                                              File "script.kodi.hue.ambilight/default.py", line 203, in update_controllers
                                                self.static_controller,
                                              File "script.kodi.hue.ambilight/resources/lib/lights.py", line 189, in __repr__
                                                return ('<{} {}>'.format(self.__class__.__name__, self.lights))
                                              File "script.kodi.hue.ambilight/resources/lib/lights.py", line 83, in __repr__
                                                self.name, self.light_id, self.hue, self.sat, self.bri, self.on))
                                            AttributeError: 'Light' object has no attribute 'hue'
                                            -->End of Python script error report<--
```
I put tow lights (bloom) y ambilight, two lights in theater and another in static.. maybe too many lights?
i will try to remove and install again. And setup ambilight first...

**Comment by JesCR** [comment]
Same error after a clean install, and another one if i check de "initial flash" option

`21:46:57.443 T:139888103769856   DEBUG: Kodi Hue: In Hue.update_controllers() instantiated following controllers <TheaterController {}> <AmbilightController {'1': <Light(AmbiDerecha) 1 hue: 12901, sat: 162, bri: 89, on: True>, '2': <Light(AmbiIzquierda) 2 hue: 12901, sat: 162, bri: 73, on: True>}> <StaticController {}>
21:46:57.444 T:139887496054528   DEBUG: Thread LanguageInvoker 139887496054528 terminating
21:46:57.445 T:139888103769856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'AmbilightController' object has no attribute 'dim_lights'
`


Rolling back to previuos version...

**Comment by mpolednik** [comment]
@JesCR Argh, some of your lights doesn't qualify as LivingWhite... nice thing to see tested :) Working on fix...

**Comment by mpolednik** [comment]
Fixed the settings process (which I consider quite a kodi feat :) ) -- now the process is way more streamlined and doesn't require OK between saving settings (the lights will disappear from available groups etc.).

The livingwhite bulbs shouldn't error out again.

**Comment by mpolednik** [comment]
Note to self (thanks for the testing above!) initial flashing doesn't work (haven't really tested that one thing and spent most of the night w/ the settings usability)... will look into it tomorow.

**Comment by hstamas** [comment]
Testing now. Promising!

First a feature request. For the "static light" which I use as my behind the TV bias light. Could you add an option to have it choose a color at random when its turned on? I have a Hue light strip behind the TV and would like that its a different color every time I use it.

I am also having some issue with setup. The light groups seem to loose their ability to be selected after  initially going into that screen. If I choose a set of lights then go back in and want to make changes the lights I chose are not green (highlighted) anymore and there doesn't seem a way to re-choose them.

Secondly I don't use the default brightness of 30 when playback starts. I want my lights completely off (all except the static/bias light). Choosing to override the default of 30 and entering 0 doesn't seem to do anything.

If it helps any. Plex has a plugin that does the same as we are trying to achieve here and has a lot more user configurability. Maybe too much so but it does allow me to do all the things Im looking to do with your plugin. Just though it might provide you with some ideas:

https://forums.plex.tv/discussion/193095/rel-hellohue-1-1-8-4-sync-and-control-your-philips-hue-lights-with-plex/p18

**Comment by JesCR** [comment]
@mpolednik thanks!!! Really, thanks for your work, impressive!
So the problem was that the lights that i use in the cealing, for theater mode, are white bulbs (and no hue parameter to apply?)...

BTW the new settings/functions are really a big step up, more clear and user friendly...
I will be very happy to test it again when you fix it.
:)

**Comment by mpolednik** [comment]
@JesCR Yep, the worst part is that the hue/sat parameters are handled everywhere, it was just diagnostic message erroring out. Have you tried to use it now? I'm pretty much fixing everything as it shows up.

@hstamas For the setup issue: are you running the newest (this) version? It should be working as expected now, with a few hacks around kodi. Seems like you're on the older one, where you actually have to save the settings (press OK after selecting the lights and OK to save the hue settings config). Newest version doesn't require that (but has small delay after button's clicked... tradeoffs :( ). I'll look into the overrides, been testing mostly defaults at the moment.

**Comment by JesCR** [comment]
@mpolednik i'm at work now (begining the day here in spain :))
i'll try again when i arrive home (+10h)

i can live without the theater mode, or even change the lights and put hue bulbs instead the white bulbs...
if it's easy to fix removing the "no-hue" lights from the list... :)

**Comment by mpolednik** [comment]
@JesCR That's what you mean -- the living white should work normally now (fixed ~8 patches ago?). Don't disassemble your home just yet ;)

**Comment by hstamas** [comment]
I might not be using the most recent version @mpolednik. As you probably hear all the time GIT is confusing to someone who doesn't work with it! What I did was change the branch to the V9 branch and downloaded the ZIP from that screen. Could you tell me what I should have done instead?

Tried it out again this morning and changing the default to 0 for brightness definitely does not work on my end. My main group of lights are still on (but dimmed) when the movie starts.

Any thoughts on that random color at startup idea I mentioned? It having that in place would allow me to completely move over to Kodi 100% from the Plex add-on Ive been using.

Thanks so much for your efforts and being open to suggestions. Do you have a donation setup for your hard work? I would be happy to buy you a beer/coffee!

**Comment by Macpatto** [comment]
@mpolednik !! Fantastic work on the patches in additions to the script.. I can tell you that I am completely satisfy with the results..  Loving it every time I watch even a music video!!

Thumbs Up!  
Keep up the good work my friend!

**Comment by mpolednik** [comment]
@hstamas Brightness 0 now should turn off the lights and you're able to choose random color. Actually the random color is chosen each time you even unpause playback -- does that make sense? Or should the color be chosen once and then just be kept the same?

**Comment by hstamas** [comment]
Random every time its unappeased is perfect for my needs @mpolednik. Thanks!

To test should I be downloading the Master branch? Will give it more testing tonight (eastern USA).

**Comment by mpolednik** [comment]
@hstamas No, download the refactoring-v9-candidate branch. I think it takes some time for github to regenerate the zip, so if you do it later you should be well set.

Also double check the settings - selecting lights, pressing OK and then opening the group dialog should already highlight the ones you selected before. If it doesn't, there is something wrong.

BTW I actually really like the static group! :D (got 3 bulbs & lightstrip, so using ambilight=lightstrip; theater=2bulbs; static=1bulb is DAMN PERFECT!)

**Comment by JesCR** [comment]
Ok, i just tested the new "new version".
First try, when i setup the "ambilight" max/min brightness (and default values are max:0 min:90 ??) i to values max:250 min:10 i get this error:

```
-->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: update() takes exactly 1 argument (3 given)
                                            Traceback (most recent call last):
                                              File "/default.py", line 311, in <module>
                                                settings = Settings()
                                              File "/settings.py", line 10, in __init__
                                                self.readxml()
                                              File "/settings.py", line 69, in readxml
                                                self.update("ambilight_min", self.ambilight_max)
                                            TypeError: update() takes exactly 1 argument (3 given)
->End of Python script error report<--
```

the second time i let "all default" and everything goes fine.

But i think that the effect is more subtle, I think it is less noticeable color and intensity... i will see a tv show tonight and check it in a "real scenario"...
👍

**Comment by JesCR** [comment]
And i've another question...
In ambilight... if i select just one light, it takes the "color" from the "Average color" of the whole screen? or the center?

If I have two lights, how do they behave? Before each light had a color more or less according to its side of the screen ... How to specify which light is on the right and which on the left?

**Comment by mpolednik** [comment]
@JesCR Wow, the ambilight sliders were swapped, good catch. Fixed.

As for the average color, it's actually quite interesting:
We look at every pixel that is in the screen and calculate "spectrum" (it should be called histogram, I'll eventually rename it), and introduce a kind of bias to make it fall within a some bucket. So if you use color bias 18, there are ~20 buckets of color pixels. Then the algorithm chooses the most represented colors in the screen and sends it over to the bulbs.

Now the ordering is actually random -- some light is determined to become the most filled bucket, others take following most filled buckets etc. I think eventually I'll have to figure out a way to select the order, but consider it really random right now.

**Comment by hstamas** [comment]
Ok had a chance to test out the newest build real quick.

Settings seem to be working as expected. Changes to group selections seem to be sticking and if I go back in to make changes, my initial selection are still there and it allows me to make changes.

With a fresh launch of Kodi everything works pretty well. Hitting play sets the lights properly. Pause also does what it should. Stop is not 100%. All lights return to their pre "Play" state except for the static light. It dims very low but never turns completely off. This happens consistantly. 

Also the random color of the static light doesn't seem very random? This was actually an issue with the Plex addon I referenced earlier. I'm not sure what the author did to make the color choices more dynamic but Kodi Hue seems to be stuck on yellow and green and at a very light saturation. 

Finally, if I do a lot of starts/pause/stops the lights seem to get out of sync with some not reacting at all and others turning off when the should be turning on and vise versa. Of course in a real world situation I would not be constantly doing this but wanted to point it out. Restarting Kodi fixes this issue.

**Comment by mpolednik** [comment]
@hstamas 

- static light should return to it's pre-playback started config (it's the only light that doesn't save every resume as it gets tricky what to save... but not impossible)
- short movie disable should work
- static random is more random

As for the sync, that is unfortunately something I know about and not so easily solvable due to transition time. We save the state of light as a new one while the light hasn't fully transitioned etc.; not sure how to solve this one.

**Comment by JesCR** [comment]
Ok, two days testing, so far so good!
Two lights as theater and two blooms as ambilight.
When i start a movie or tvshow the ceiling lights dim and the ambilights starts to do his magic.
I wonder if the dim value of the teather lights could be changed, i wish that the theater lighst turn off instead of dimming. I see some override options in the setup, but i'm not sure what are they for so i didn't touch :)

And the static lights... what are they for? it's something like the theater?  i should try it but i don't wanto to "break" anything...

Thanks again!

**Comment by mpolednik** [comment]
@JesCR Override is exactly what you're looking for - it changes the brightness of dimmed/undimmed group. Brightness = 0 means turn off (hopefully got that part finally right.

Static is kinda inverse theater mode - it turns on the lights when movie plays and turns them off on pause. You shouldn't worry about breaking anything -- everything can be fixed. :)

I'll update the documentation and versioning and slowly merge this to a master (where it'll get higher exposure and people will find all kinds of bugs :( ).

**Comment by JesCR** [comment]
Ok!
I try it at night!
This is the best hue addon for kodi, it deserves to be in the official repository.
i try to take a viedeo of my setup running tonight and share with you :)

**Comment by jpk8201** [comment]
Finally the Hue Bridge works again. Thanks for the great work!

**Comment by hstamas** [comment]
Tested 1.0 for a few mi jets tonight. Very promising!

All issues that I have pointed out seem to be mainly resolved except for once or twice I had a light not reset to initial brightness on stop and once one did not turn Barack on at all. Again during testing I have been throwing a lot of "play/pause/stops" at the plugin so that may be triggering some sync instability again. I will have a chance to do a real world test tomorrow night and will report back. Thanks again for all your hard work @mpolednik!

**Comment by JesCR** [comment]
hi!
i opened a new issue with my problems, can't get "discover brigde" to work in a nvidia shield tv.
And when i copy settings from my old device (qnap nas) the ambilight lights don't work :/
https://github.com/mpolednik/script.kodi.hue.ambilight/issues/37

BTW works perfectly in the qnap nas!

**Pull request merged**
