### PR TITLE
Fix from other repos

### PR DESCRIPTION
**Pull request by Moyster**
Hey there,

It seems your repo missed a commit from michaelrcarrol's (Update tools.py) which add Lighstrip+ ( see https://github.com/michaelrcarroll/script.kodi.hue.ambilight/pull/19 ) to fullspectrum

The two other commits from koying fix what the commit msgs say, pretty useful when using CinemaVision or playlist, the lights kind of behave wierdly in between two vids in a playlist.

### CODE REVIEW

**Comment by mpolednik** [comment]
Will test the non-lightstrip changes to make sure it doesn't break anything important, ack for now. Btw, how well does lightstrip work with this plugin?

**Comment by mpolednik** [comment]
Small update, I prefer the light detection from #14 - rebase will be needed.

**Comment by Moyster** [comment]
Hoi,
I totally forgot about that, it's not that important tho, I'll rebase at some point this month :)

Any updates incoming ?

**Comment by mpolednik** [comment]
Haven't had much time at the moment, but one of the progress I made is considering a lightstrip. :)

**Comment by Moyster** [comment]
Hello,

I might ask you to reconsider : 
"Small update, I prefer the light detection from #14 - rebase will be needed."

I will try a bit more later on tonight but it broke the plugin on ARM (at least on my android box) whereas my repo works correctly.

Greetings

**Comment by mpolednik** [comment]
Could you do GET 	/api/<username>/lights and share the output at least of the lightstrip? It's interesting why it'd broke as #14 uses what Philips Hue API kind-of suggests.

**Comment by mpolednik** [comment]
Sorry, github can't deal with scope symbols properly. GET /api/YOURUSERNAME/lights

**Comment by Moyster** [comment]
I'm gonna try a few stuff and rebase the changes of this PR during the day

**Pull request closed without merging**
